### ISSUE TITLE
slope function returns integer

### ISSUE THREAD

**Issue by gutabeshu** [hyriver/py3dep#70]
### What happened?

when extracting slope with huc12 geometry, `slope_ = py3dep.get_map("Slope Degrees", geometry, resolution=30) ` returns only in integers. see attached plot (please ignore the red dots on the plot, they are quantile values and intended for unrelated purposes)
![slope_hs](https://github.com/hyriver/py3dep/assets/40370576/0ff2d1c3-97ec-4944-ab2c-4b46b3be9ea2)

### What did you expect to happen?

expected a float 

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<py3dep                 0.16.2>

</details>

**Comment by cheginit** [comment]
Can you please try this and compare with what you have?

```python
import py3dep
import xrspatial

dem10 = py3dep.get_dem(geom, 10, gem_crs)
slope30 = xrspatial.slope(dem10).coarsen(x=3, y=3, boundary="trim").mean()
```

Note: You can install `xrspatial` with `micromamba install -c conda-forge xarray-spatial`

**Comment by cheginit** [comment]
Ok, the values are in the same range. The issue is most likely due to using 30 m resolution. I think the underlying data source at 30 m resolution does not have enough accuracy to require saving the results in float. So, since integers take much less storage, the data is usually stored in int format.

I typically get the DEM at 10 m resolution, even if I don't need that much accuracy, then upscale it (coarsen) to the desired resolution. If your area of interest is huge, you can try using `py3dep.get_dem_vrt` function. You can then compute other topo features using `xrspatial`.
