### ISSUE TITLE
3DEP Location Moved?

### ISSUE THREAD

**Issue by TDFSE** [hyriver/py3dep#74]
### What happened?

Have been getting:

> py3dep.exceptions.ServiceUnavailableError: Service is currently not available, try again later:
> https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer

When using get_dem() and get_map() for 1m data. Checking here:

https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer?request=GetCapabilities&service=WMS

I am not seeing the 1m (or other resolution DEM data) being available. However, it does seem to be appearing here:
https://index.nationalmap.gov/arcgis/rest/services/3DEPElevationIndex/MapServer
https://index.nationalmap.gov/arcgis/services/3DEPElevationIndex/MapServer/WMSServer?request=GetCapabilities&service=WMS

Am unsure if they are moving things around or if I'm configuring something improperly, but this was working until recently, and have tried multiple input bounding boxes.

### Minimal Complete Verifiable Example

```Python
Bounding box: (-79.45456626811541, 36.75864853448827, -79.41996079283527, 36.81001992450675)
Resolution: 1
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
py3dep.exceptions.ServiceUnavailableError: Service is currently not available, try again later:
https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer
```

### Environment

<details>
SYS INFO
--------
commit: 01524ce7e16ae0cbd85e410c0be1fdf65a2f6722
python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('English_United States', '1252')

PACKAGE                VERSION
-------------------------------
async-retriever        0.17.1
pygeoogc               0.17.1
pygeoutils             0.17.1
py3dep                 0.17.1
pynhd                  N/A
pygridmet              N/A
pydaymet               N/A
hydrosignatures        N/A
pynldas2               N/A
pygeohydro             N/A
aiohttp                3.11.8
aiohttp-client-cache   0.12.4
aiosqlite              0.20.0
cytoolz                1.0.0
ujson                  5.10.0
defusedxml             0.7.1
joblib                 1.4.2
multidict              6.1.0
owslib                 0.32.0
pyproj                 3.7.0
requests               2.32.3
requests-cache         1.2.1
shapely                2.0.6
url-normalize          1.4.3
urllib3                2.2.3
yarl                   1.18.0
geopandas              1.0.1
netcdf4                1.7.2
numpy                  2.1.3
rasterio               1.4.2
rioxarray              0.17.0
scipy                  1.14.1
xarray                 2024.11.0
click                  8.1.7
pyflwdir               N/A
networkx               N/A
pyarrow                N/A
folium                 N/A
h5netcdf               N/A
matplotlib             N/A
pandas                 2.2.3
numba                  N/A
bottleneck             N/A
py7zr                  N/A
pyogrio                0.10.0
-------------------------------

</details>

**Comment by cheginit** [comment]
The issue is that you're requesting high resolution data for a relatively large area, the result has around 17.6 million pixels! Due to the large request, it might fail on the first (a few tries). I was able to run this:

```python
bbox = (-79.45456626811541, 36.75864853448827, -79.41996079283527, 36.81001992450675)
dem = py3dep.get_dem(bbox, 1)
```

and get results after trying two times.

Most importantly, note that when using `get_map` you're requesting data from 3DEP's dynamic layer, meaning that you can request for any resolution, the web service will always interpolate the source DEMs and return the data at your requested resolution. So you can request for 2 or 3 or any positive number. However, when using `get_dem` if you request for 10, 30, or 60 m resolutions, DEMs are obtained from 3DEP's static datasets, so they tend to be faster. I recommend getting 10-m resolution unless you really need the 1-m resolution, which in that case you need to be careful since 1-m data still does not cover the whole US, so depending on the region of your request you might end up with some issues in the data.

**Comment by TDFSE** [comment]
Understood - thank you! I'll see if I can write something to break the geometry into smaller polygons if it is over a certain size - greatly appreciate the feedback!

**Comment by cheginit** [comment]
Py3DEP does break big requests into smaller regions, under-the-hood, so you don't have to do that. You just need to run it a couple of times and make sure to check the results carefully for any artifacts in the data. If there are, you can increase the resolution to 2 or 3, until you get satisfactory results.

**Comment by TDFSE** [comment]
Tested it out a few more times this morning, with the same result, however once I deleted _pycache and cache folders, it worked! Possible it had saved the response that was causing the issue, and was falling back to that response? Should I make a habit of clearing the cache if bad responses occur?

**Comment by cheginit** [comment]
That's odd, since technically it shouldn't cache the failed results. Please update to the latest version (v0.18) and try again.

Note that all HyRiver packages refresh caches every week, so you don't really have to worry about it, I rarely do. But, sometimes when an issue persists, disabling cache is the first that I do:

```python
import os

os.environ["HYRIVER_CACHE_DISABLE"] = "true"
```

If this solves the issue, then I manually delete the cache.
